name: cralwer

on:
  push:
    branches: [main]
  
jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt        
    - name: test
      env:
        telegram_token: ${{ secrets.TELEGRAMTOKEN }}
      run: |
        python test.py
    - name: Commits
      run: |
        git config --local user.email "your@email"
        git config --local user.name "Auto_Crawler_Name" # 커밋에 포함될 이름
        git add news.json
        git commit -m "Auto - Update data with Crawling" # 커밋 메세지
